camunda/camunda-webapp-translations

locales/de.json
=> small typo

cockpit/en.json
related to [CAM-10867](https://app.camunda.com/jira/browse/CAM-10867)
=> [CAM-10867] In Cockpit, add input field to definition views to select version

cockpit/en.json
related to [CAM-10867](https://app.camunda.com/jira/browse/CAM-10867)
=> [CAM-10867] add input field to definition views to select version

admin/de.json, cockpit/de.json, tasklist/de.json, welcome/de.json
invalid json results in error messages in webapps.
=> invalid json in de.json due to missing comma

admin/pt-BR.json
Add new tags of translate Camunda 12
=> Update pt-BR Camunda 12 for Brazilian

cockpit/en.json
=> CAM-3384 - feat(variable-add): add datepicker to modal

admin/pt-BR.json
I discovered a strange character in the middle of the JSON file
=> CAM-11780: Adjustment in the Admin JSON file

admin/en.json
=> feat(admin): Add new execution metrics

README.md
=> CAM-11910: chore(project): update readme

cockpit/en.json
=> CAM-12076 - fix(batches): hide ended batches with config flag

admin/en.json, welcome/en.json
=> fix(password-widget): add user data password policy rule

admin/en.json
Added a space between 'sign in'
=> fix (bug fix): Fix typo

cockpit/en.json
=> fix(cockpit): fix message when adding a variable to a batch

admin/en.json, cockpit/en.json, tasklist/en.json, welcome/en.json
=> fix(wording): add more detail to telemetry details

cockpit/en.json
=> feat(search): improve filtering by incident type

cockpit/en.json
=> feat(repository): display preview of HTML files

cockpit/en.json, tasklist/en.json
=> feat(task): add filter for tasks without due date

cockpit/en.json
=> chore(cockpit): show error message in preview

admin/en.json
=> feat(en): change metrics label

admin/en.json
=> feat(admin): configure SYSTEM permissions for users

cockpit/de.json, cockpit/en.json
=> feat(batch): batch user translation

cockpit/en.json
=> CAM-14769: Improve the safety of executing a batch operation on the Batch Operation page
